[phases.setup]
# Ensure Python is present for Nixpacks Python phase, plus native deps for OpenCV/MediaPipe
nixPkgs = ['python311', 'pkg-config', 'glib', 'zlib']
cmds = [
  'apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender1 libgomp1 && ldconfig'
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
