[phases.setup]
nixPkgs = ['...', 'libGL', 'libglvnd', 'pkg-config']

[phases.install]
dependsOn = ['setup']

[phases.build]
dependsOn = ['install']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
